
/*! [mat-rt v2.1] runtime patch: unify parents & prevent duplicate widgets */
(() => {
  if (window.__LM_MAT_RT_ONCE) return; // singleton guard
  window.__LM_MAT_RT_ONCE = true;

  const log = (...a) => console.log("[mat-rt]", ...a);
  const warn = (...a) => console.warn("[mat-rt] warn", ...a);

  function first(q) { return document.querySelector(q); }
  function all(q) { return Array.from(document.querySelectorAll(q)); }

  // Keep a tight scope: we only touch material pane
  function pane() { return document.getElementById("panel-material") || document.getElementById("pane-material"); }

  // Remove duplicate numeric badges & ghost ranges generated by past injections
  function dedupe() {
    const p = pane();
    if (!p) return;
    // Numeric badges: keep the first, remove the rest
    const badges = all("#pm-opacity .lm-val, #pm-opacity .lm-badge, .pm-opacity-value");
    if (badges.length > 1) badges.slice(1).forEach(n => n.remove());

    // Opacity range: ensure only one input[type=range] within pm-opacity
    const ranges = all("#pm-opacity input[type=range]");
    if (ranges.length > 1) ranges.slice(1).forEach(n => n.remove());

    // Old leftover rows having empty height
    all("#pm-opacity .ghost, #pm-opacity .dup, #pm-opacity .lm-ghost").forEach(n => n.remove());
  }

  function ensureBadge() {
    const host = first("#pm-opacity");
    const range = first("#pm-opacity input[type=range]");
    if (!host || !range) return;

    let badge = host.querySelector(".lm-val");
    if (!badge) {
      badge = document.createElement("span");
      badge.className = "lm-val";
      badge.style.marginLeft = "8px";
      badge.style.fontVariantNumeric = "tabular-nums";
      host.appendChild(badge);
    }
    const v = Number(range.value);
    badge.textContent = (isFinite(v) ? v : 1).toFixed(2);
  }

  function wire() {
    const p = pane();
    if (!p) {
      warn("material pane missing");
      return;
    }
    log("wired");
    dedupe();
    ensureBadge();

    const range = first("#pm-opacity input[type=range]") || first("#opacityRange");
    if (range && !range.__lm_val_bound) {
      range.addEventListener("input", () => {
        ensureBadge();
      }, { passive: true });
      range.__lm_val_bound = true;
    }

    // Also dedupe on DOM mutations within material pane
    const mo = new MutationObserver(() => { dedupe(); ensureBadge(); });
    mo.observe(p, { childList: true, subtree: true });
  }

  // Give time for host to synthesize
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", wire);
  } else {
    setTimeout(wire, 0);
  }
})();
